### ISSUE TITLE
Hi, Please Add Me as a Collaborator

### ISSUE THREAD

**Issue by HereIsKevin** [pythonmcpi/StickerTool#5]
This is **obviously** Kevin, please invite me, as I want to help you (while learning PyGame in the process).

**Comment by HereIsKevin** [comment]
It seems that you have a lot of followers, including people called "Hallowizer" and "aehmttw". Who are they?

**Comment by HereIsKevin** [comment]
Speed up, Mason.

**Comment by HereIsKevin** [comment]
---
# WHEN WILL YOU RESPOND!!!!!!!!!!
---

**Comment by pythonmcpi** [comment]
Closed for irrelevance.
